### ISSUE TITLE
Reactor doesn't work with connectTCP()

### ISSUE THREAD

**Issue by ezehiel** [mtearle/twisted-reactor-npyscreen#1]
Hi,
First of all - great job!. I came across the problem with your reactor however, when I was writing client application to remote server with npyscreen. seems like the reactor doesn't work at all (on Twisted side) when connecting to the server. I took a liberty of changing the code a little bit, which should render it usable in my case (not sure if it breaks the rest - hasn't been tested).

Please find modified version below:
https://github.com/scltd/main/blob/master/npyscreenreactor.py

**Comment by mtearle** [comment]
Thanks :)

I've only really tested the code running as a server for the applications that I've written.   
I've incorporated and committed an updated version including your fixes.

Do you have a good test example for connectTCP() and npyscreen?

**Comment by ezehiel** [comment]
Sure, now a bit away from the computer but I can submit it today in the evening (CEST)

**Comment by ezehiel** [comment]
And here is the test case for the reactor : https://github.com/scltd/main/blob/master/testClient.py

**Comment by mtearle** [comment]
Thanks!  I've tested it against my updates successfully.   I'll work on putting together an example to include in my repository and let the npyscreen developers know of the update.

**Comment by ezehiel** [comment]
Cool this sound really good. Thanks.

**Comment by mtearle** [comment]
Working example added for client.
